@host = localhost:8088
// Register User
POST http://{{host}}/api/user/register HTTP/1.1
content-type: application/json

{
    "name": "Taro Yamada",
    "username": "taro.yamada",
    "email": "taro@go.com",
    "password": "123465789"
}

###